/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on 11/09/2010, 11:08:03
 */

package vm.gui;

/**
 *
 * @author cadi
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        upPanel = new javax.swing.JPanel();
        descPC = new javax.swing.JLabel();
        labelPC = new javax.swing.JLabel();
        descInstruAtual = new javax.swing.JLabel();
        labelInstruAtual = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        buttonExecute = new javax.swing.JButton();
        leftPanel = new javax.swing.JPanel();
        dsRegDst = new javax.swing.JLabel();
        labelRegDst = new javax.swing.JLabel();
        dsJump = new javax.swing.JLabel();
        labelJump = new javax.swing.JLabel();
        dsBranch = new javax.swing.JLabel();
        labelBranch = new javax.swing.JLabel();
        dsMemRead = new javax.swing.JLabel();
        labelMemRead = new javax.swing.JLabel();
        dsMentoReg = new javax.swing.JLabel();
        labelMemtoReg = new javax.swing.JLabel();
        dsALUOp = new javax.swing.JLabel();
        labelALUOp = new javax.swing.JLabel();
        dsMemWrite = new javax.swing.JLabel();
        labelMemWrite = new javax.swing.JLabel();
        dsALUSrc = new javax.swing.JLabel();
        labemALUSrc = new javax.swing.JLabel();
        dsRegWrite = new javax.swing.JLabel();
        labelRegWrite = new javax.swing.JLabel();
        dsZero = new javax.swing.JLabel();
        labelZero = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuExibir = new javax.swing.JMenu();
        menuItemRegistradores = new javax.swing.JMenuItem();
        menuItemMemoria = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAQUINA VIRTUAL MONOCICLO MUITO LOCA");
        setResizable(false);

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mainPanel.setLayout(new java.awt.BorderLayout(2, 2));

        upPanel.setLayout(new java.awt.GridLayout(2, 2, 0, 2));

        descPC.setText("PC :");
        upPanel.add(descPC);

        labelPC.setText("0");
        upPanel.add(labelPC);

        descInstruAtual.setText("Instrução executada :");
        upPanel.add(descInstruAtual);

        labelInstruAtual.setText("None");
        upPanel.add(labelInstruAtual);

        mainPanel.add(upPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonExecute.setText("Executar");
        buttonExecute.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bottomPanel.add(buttonExecute);

        mainPanel.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        leftPanel.setLayout(new java.awt.GridLayout(10, 2, 5, 0));

        dsRegDst.setText("RegDst:");
        leftPanel.add(dsRegDst);

        labelRegDst.setText("0");
        leftPanel.add(labelRegDst);

        dsJump.setText("Jump:");
        leftPanel.add(dsJump);

        labelJump.setText("0");
        leftPanel.add(labelJump);

        dsBranch.setText("Branch:");
        leftPanel.add(dsBranch);

        labelBranch.setText("0");
        leftPanel.add(labelBranch);

        dsMemRead.setText("MemRead:");
        leftPanel.add(dsMemRead);

        labelMemRead.setText("0");
        leftPanel.add(labelMemRead);

        dsMentoReg.setText("MemtoReg:");
        leftPanel.add(dsMentoReg);

        labelMemtoReg.setText("0");
        leftPanel.add(labelMemtoReg);

        dsALUOp.setText("ALUOp:");
        leftPanel.add(dsALUOp);

        labelALUOp.setText("0");
        leftPanel.add(labelALUOp);

        dsMemWrite.setText("MemWrite:");
        leftPanel.add(dsMemWrite);

        labelMemWrite.setText("0");
        leftPanel.add(labelMemWrite);

        dsALUSrc.setText("ALUSrc:");
        leftPanel.add(dsALUSrc);

        labemALUSrc.setText("0");
        leftPanel.add(labemALUSrc);

        dsRegWrite.setText("RegWrite:");
        leftPanel.add(dsRegWrite);

        labelRegWrite.setText("0");
        leftPanel.add(labelRegWrite);

        dsZero.setText("Zero:");
        leftPanel.add(dsZero);

        labelZero.setText("0");
        leftPanel.add(labelZero);

        mainPanel.add(leftPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        mainPanel.add(rightPanel, java.awt.BorderLayout.LINE_END);

        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vm_imagem.png"))); // NOI18N
        centerPanel.add(labelImage);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        menuArquivo.setMnemonic('a');
        menuArquivo.setText("Arquivo");

        menuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menuItemAbrir.setMnemonic('a');
        menuItemAbrir.setText("Carregar Instruções");
        menuArquivo.add(menuItemAbrir);

        menuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSair.setMnemonic('s');
        menuItemSair.setText("Sair");
        menuArquivo.add(menuItemSair);

        menuBar.add(menuArquivo);

        menuExibir.setMnemonic('e');
        menuExibir.setText("Exibir");

        menuItemRegistradores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemRegistradores.setMnemonic('r');
        menuItemRegistradores.setText("Registradores");
        menuExibir.add(menuItemRegistradores);

        menuItemMemoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        menuItemMemoria.setMnemonic('m');
        menuItemMemoria.setText("Memória");
        menuExibir.add(menuItemMemoria);

        menuBar.add(menuExibir);

        menuAjuda.setMnemonic('j');
        menuAjuda.setText("Ajuda");
        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Vamo que vamo grupo Herança");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton buttonExecute;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel descInstruAtual;
    private javax.swing.JLabel descPC;
    private javax.swing.JLabel dsALUOp;
    private javax.swing.JLabel dsALUSrc;
    private javax.swing.JLabel dsBranch;
    private javax.swing.JLabel dsJump;
    private javax.swing.JLabel dsMemRead;
    private javax.swing.JLabel dsMemWrite;
    private javax.swing.JLabel dsMentoReg;
    private javax.swing.JLabel dsRegDst;
    private javax.swing.JLabel dsRegWrite;
    private javax.swing.JLabel dsZero;
    private javax.swing.JLabel labelALUOp;
    private javax.swing.JLabel labelBranch;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelInstruAtual;
    private javax.swing.JLabel labelJump;
    private javax.swing.JLabel labelMemRead;
    private javax.swing.JLabel labelMemWrite;
    private javax.swing.JLabel labelMemtoReg;
    private javax.swing.JLabel labelPC;
    private javax.swing.JLabel labelRegDst;
    private javax.swing.JLabel labelRegWrite;
    private javax.swing.JLabel labelZero;
    private javax.swing.JLabel labemALUSrc;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuExibir;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemMemoria;
    private javax.swing.JMenuItem menuItemRegistradores;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables

}
